server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  application:
    name: product-backend-application

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5842/product-db
    username: postgres
    password: m070498m
    platform: postgresql
    initialization-mode: always
    initialize: true
    maxActive: 3

  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USER:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

app-config:
  services:
    sales: http://${SALES_HOST:localhost}:${SALES_PORT:8082}

  secrets:
    api-secret: ${API_SECRET:MjgxMDExZTYtNWQ4OS00NWI5LTg0OGMtYjVhZTI0OWIzYmM2}

  rabbit:
    exchange:
      product: product.topic

    routingKey:
      product-stock: product-stock-update.routingKey
      sales-confirmation: sales-confirmation.routingKey

    queue:
      product-stock: product-stock-update.queue
      sales-confirmation: sales-confirmation.queue